name: golangci-lint
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - run: sudo apt-get update
    - run: >
        sudo apt-get install -y \
          libx11-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libglx-dev \
          libgl-dev \
          libxxf86vm-dev
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.2
